export const channels = {
  disabled: '停用',
  title: '分发渠道', search: '搜索渠道', add: '添加渠道', name: '渠道名称', client: '输出客户端', edit: '编辑', remove: '删除渠道', deletePrompt: '删除“{{name}}”？该渠道的订阅地址将不再可用。', save: '保存更改', saved: '渠道已保存', empty: '暂无渠道', back: '返回', nodes: '节点选择', rules: '订阅规则', organizer: '节点整理', distribution: '分发设置', preview: '订阅预览', enabled: '启用', nameRequired: '请输入名称', unsaved: '有未保存的更改', discard: '放弃更改', leave: '放弃未保存的渠道更改？', cancel: '取消', done: '完成', refresh: '刷新节点',
  prefix: '名称前缀', exclusions: '排除名称', exclusionsHint: '每行一项', sort: '节点排序', original: '原始顺序', byName: '按名称', deduplicate: '去重', incompatible: '不兼容节点', skip: '跳过并记录', stop: '阻止生成', legacyTags: '排除标签', legacyTypes: '排除协议',
  newNodes: '新增节点策略', include: '自动选入渠道', exclude: '手动选入', template: '当前模板', defaultTemplate: '默认配置', customTemplate: '自定义配置', editTemplate: '编辑模板', templateCode: '原生配置', validate: '校验', valid: '模板结构校验通过', templateSaved: '模板已保存', saveTemplate: '保存模板', formatConflict: '输出客户端已更改，请检查规则集格式及模板。', copy: '复制', copied: '已复制', failedNodes: '{{count}} 个节点未生成，请查看诊断。', diagnostics: '生成诊断',
  groups: '规则组', addGroup: '添加规则组', editGroup: '编辑规则组', groupName: '组名称', matches: '匹配配置', manualCount: '{{count}} 条规则', remoteCount: '{{count}} 个规则集', state: '状态', actions: '操作', candidates: '候选节点', defaultExit: '默认出口', fallback: '未匹配流量', direct: '直连', reject: '拒绝', follow: '跟随组默认', missingNode: '不可用节点', moveUp: '上移', moveDown: '下移', deleteGroup: '删除规则组', deleteRule: '删除规则',
  addRule: '添加规则', addRemote: '添加规则集', editRule: '编辑规则', editRemote: '编辑规则集', ruleKind: '匹配类型', domain: '域名', domain_suffix: '域名后缀', domain_keyword: '域名关键字', ip_cidr: 'IP / CIDR', matchValue: '匹配内容', exit: '流量出口', ruleName: '名称', url: '来源网址', acceleration: 'GitHub 文件加速', sourceFormat: '源格式', chooseFormat: '选择格式', behavior: '规则类型', interval: '更新间隔（秒）', selectAll: '全选', selectNone: '取消全选', unavailable: '当前不可用', invalidRule: '请检查匹配内容、来源网址或更新间隔。', formatPending: '待选择格式',
  legacy: '此渠道保留 Loon 输出。切换客户端并保存后可使用规则与模板。', publicHost: '原渠道对外地址', enabledLabel: '渠道启用', selectedByGroup: '此节点仍被规则组或默认出口引用，请先调整相关出口。', legacyFilters: '已有排除条件',
} as const;
