# SPDX-License-Identifier: GPL-3.0-or-later
# Managed by sing-box-panel system install.
d /etc/sing-box-panel 0750 root sing-box-panel -
d /var/lib/sing-box-panel 0700 sing-box-panel sing-box-panel -
