[General]
skip-proxy = 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,localhost,*.local
bypass-tun = 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16
dns-server = system,119.29.29.29,223.5.5.5
doh-server = https://223.5.5.5/dns-query,https://120.53.53.53/dns-query
ip-mode = ipv4-only
allow-wifi-access = false
allow-udp-proxy = true
udp-fallback-mode = REJECT
interface-mode = Auto
test-timeout = 5

[MITM]
enable = false
skip-server-cert-verify = false
