// Code generated by go tool singbox-support generate; DO NOT EDIT.
// SPDX-License-Identifier: GPL-3.0-or-later

package singbox

var generatedVersions = []Version{
	{ExactVersion: "1.13.19", InboundFamily: "1.13", Upstream: Upstream{Tag: "v1.13.19", Commit: "b5ebaa1fc0f2b94256180b95468e73ef53caa27d", ModuleSum: "h1:oHoleLx60mkTHabEsIV8X+z5LU5CUsYfehQc8P/KvVo=", GoModSum: "h1:4E8WvF7Vi60N1NtPw1CeG994J/yiJZZkty5dKKwG+V0="}, Profiles: map[string]Profile{
		"amd64": {AssetName: "sing-box-1.13.19-linux-amd64-musl.tar.gz", URL: "https://github.com/SagerNet/sing-box/releases/download/v1.13.19/sing-box-1.13.19-linux-amd64-musl.tar.gz", SHA256: "150456f94fcf936fc2519de28d856422fb671a1ff181cd909b78f20e208fdcb8", Size: 24753732, Features: []string{"badlinkname", "tfogo_checklinkname0", "with_acme", "with_ccm", "with_clash_api", "with_dhcp", "with_gvisor", "with_musl", "with_naive_outbound", "with_ocm", "with_quic", "with_tailscale", "with_utls", "with_wireguard"}},
		"arm64": {AssetName: "sing-box-1.13.19-linux-arm64-musl.tar.gz", URL: "https://github.com/SagerNet/sing-box/releases/download/v1.13.19/sing-box-1.13.19-linux-arm64-musl.tar.gz", SHA256: "5146181884310ea2381e085ef504005c81bd09f80721542127efb0a73f12cd2f", Size: 22735134, Features: []string{"badlinkname", "tfogo_checklinkname0", "with_acme", "with_ccm", "with_clash_api", "with_dhcp", "with_gvisor", "with_musl", "with_naive_outbound", "with_ocm", "with_quic", "with_tailscale", "with_utls", "with_wireguard"}},
	}},
	{ExactVersion: "1.14.0", InboundFamily: "1.14", Upstream: Upstream{Tag: "v1.14.0", Commit: "0b8995879f29a9b98ee027bc17b75e101445b238", ModuleSum: "h1:c2x4MxM4ZJ2i11W2UiAeRJULJDSeOAF/W7Wl5F7eORg=", GoModSum: "h1:CN1I6jgtUwF1ON5dmUrq9JVdKFXrhY4scZyjE1rihs8="}, Profiles: map[string]Profile{
		"amd64": {AssetName: "sing-box-1.14.0-linux-amd64-musl.tar.gz", URL: "https://github.com/SagerNet/sing-box/releases/download/v1.14.0/sing-box-1.14.0-linux-amd64-musl.tar.gz", SHA256: "d2d6b4543d850269214ced70ffe41b13b1595baa1b6f9c016466abfba162c4d4", Size: 32481765, Features: []string{"badlinkname", "tfogo_checklinkname0", "with_acme", "with_ccm", "with_clash_api", "with_cloudflared", "with_dhcp", "with_gvisor", "with_musl", "with_naive_outbound", "with_ocm", "with_openconnect", "with_openvpn", "with_quic", "with_tailscale", "with_usbip", "with_utls", "with_wireguard"}},
		"arm64": {AssetName: "sing-box-1.14.0-linux-arm64-musl.tar.gz", URL: "https://github.com/SagerNet/sing-box/releases/download/v1.14.0/sing-box-1.14.0-linux-arm64-musl.tar.gz", SHA256: "1811c446a4957edee1b62ed2363607f8e99e1f7b6d88179719251d7ed5f30169", Size: 29685215, Features: []string{"badlinkname", "tfogo_checklinkname0", "with_acme", "with_ccm", "with_clash_api", "with_cloudflared", "with_dhcp", "with_gvisor", "with_musl", "with_naive_outbound", "with_ocm", "with_openconnect", "with_openvpn", "with_quic", "with_tailscale", "with_usbip", "with_utls", "with_wireguard"}},
	}},
}
