// Code generated by go tool singbox-support generate; DO NOT EDIT.
// SPDX-License-Identifier: GPL-3.0-or-later

package singbox

var generatedVersions = []Version{
	{ExactVersion: "1.11.15", Family: "1.11", Upstream: Upstream{Tag: "v1.11.15", Commit: "bc35aca01704497c179da1a03e45ad8e32f1a51b"}, AdapterRevision: "2", Profiles: map[string]Profile{
		"amd64": {AssetName: "sing-box-1.11.15-linux-amd64.tar.gz", URL: "https://github.com/SagerNet/sing-box/releases/download/v1.11.15/sing-box-1.11.15-linux-amd64.tar.gz", SHA256: "950af37eb2d7e55dddae34a18411cd617303fd99d2dc75bc76b6dd9fcd97d9c5", Size: 12343812, Features: []string{"with_acme", "with_clash_api", "with_dhcp", "with_ech", "with_gvisor", "with_quic", "with_reality_server", "with_utls", "with_wireguard"}},
		"arm64": {AssetName: "sing-box-1.11.15-linux-arm64.tar.gz", URL: "https://github.com/SagerNet/sing-box/releases/download/v1.11.15/sing-box-1.11.15-linux-arm64.tar.gz", SHA256: "20a6a9cd259a95411599f811a5066513a98db63705a51121252ad27daf96c029", Size: 11276002, Features: []string{"with_acme", "with_clash_api", "with_dhcp", "with_ech", "with_gvisor", "with_quic", "with_reality_server", "with_utls", "with_wireguard"}},
	}},
	{ExactVersion: "1.12.25", Family: "1.12", Upstream: Upstream{Tag: "v1.12.25", Commit: "73bfb99ebce7923c485435e4faf8571b412065a9"}, AdapterRevision: "2", Profiles: map[string]Profile{
		"amd64": {AssetName: "sing-box-1.12.25-linux-amd64.tar.gz", URL: "https://github.com/SagerNet/sing-box/releases/download/v1.12.25/sing-box-1.12.25-linux-amd64.tar.gz", SHA256: "a1ec76e2b6b139eb747a1b1ebee7d14b8d4be5a833596cad8070a31ef960301f", Size: 16523863, Features: []string{"with_acme", "with_clash_api", "with_dhcp", "with_gvisor", "with_quic", "with_tailscale", "with_utls", "with_wireguard"}},
		"arm64": {AssetName: "sing-box-1.12.25-linux-arm64.tar.gz", URL: "https://github.com/SagerNet/sing-box/releases/download/v1.12.25/sing-box-1.12.25-linux-arm64.tar.gz", SHA256: "719b76196c8b31efa636b2d8f669e314547e0da0a5ab38a75e1882d307bbd154", Size: 14962486, Features: []string{"with_acme", "with_clash_api", "with_dhcp", "with_gvisor", "with_quic", "with_tailscale", "with_utls", "with_wireguard"}},
	}},
	{ExactVersion: "1.13.19", Family: "1.13", Upstream: Upstream{Tag: "v1.13.19", Commit: "b5ebaa1fc0f2b94256180b95468e73ef53caa27d"}, AdapterRevision: "2", Profiles: map[string]Profile{
		"amd64": {AssetName: "sing-box-1.13.19-linux-amd64.tar.gz", URL: "https://github.com/SagerNet/sing-box/releases/download/v1.13.19/sing-box-1.13.19-linux-amd64.tar.gz", SHA256: "ef88a9e577d474210867bd708933d042e9b70106529df2656182c9db90106aa1", Size: 23928553, Features: []string{"badlinkname", "tfogo_checklinkname0", "with_acme", "with_ccm", "with_clash_api", "with_dhcp", "with_gvisor", "with_naive_outbound", "with_ocm", "with_purego", "with_quic", "with_tailscale", "with_utls", "with_wireguard"}},
		"arm64": {AssetName: "sing-box-1.13.19-linux-arm64.tar.gz", URL: "https://github.com/SagerNet/sing-box/releases/download/v1.13.19/sing-box-1.13.19-linux-arm64.tar.gz", SHA256: "7fe3597a95a3c5ad67477b1d7653b9ce097e0be7c676758eba1fcf558f353d57", Size: 22122605, Features: []string{"badlinkname", "tfogo_checklinkname0", "with_acme", "with_ccm", "with_clash_api", "with_dhcp", "with_gvisor", "with_naive_outbound", "with_ocm", "with_purego", "with_quic", "with_tailscale", "with_utls", "with_wireguard"}},
	}},
}
