# SPDX-License-Identifier: GPL-3.0-or-later
# Opt-in system service override for TUN, transparent proxy, and low ports.
# Review the capabilities against the enabled sing-box configuration first.

[Service]
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW
PrivateDevices=false
DevicePolicy=closed
DeviceAllow=/dev/net/tun rw
