// SPDX-License-Identifier: GPL-3.0-or-later

package main

import (
	"bytes"
	"fmt"
	"slices"
	"strings"
)

func render(components []component) ([]byte, error) {
	if len(components) == 0 {
		return nil, fmt.Errorf("cannot render an empty third-party notice")
	}
	components = slices.Clone(components)
	slices.SortFunc(components, func(left, right component) int {
		if result := strings.Compare(left.Name, right.Name); result != 0 {
			return result
		}
		if result := strings.Compare(left.Version, right.Version); result != 0 {
			return result
		}
		return strings.Compare(left.Ecosystem, right.Ecosystem)
	})
	documents := make(map[string]*licenseDocument)
	for _, value := range components {
		if value.Name == "" || value.Version == "" || value.Source == "" || value.LicenseID == "" || len(value.Files) == 0 {
			return nil, fmt.Errorf("component %q has incomplete notice metadata", value.identity())
		}
		for _, file := range value.Files {
			document, ok := documents[file.Digest]
			if !ok {
				document = &licenseDocument{Digest: file.Digest, Content: file.Content}
				documents[file.Digest] = document
			} else if !bytes.Equal(document.Content, file.Content) {
				return nil, fmt.Errorf("SHA-256 collision between license documents %s", file.Digest)
			}
			document.Uses = append(document.Uses, documentUse{Component: value.identity(), Path: file.Path})
		}
	}

	var output bytes.Buffer
	output.WriteString("THIRD-PARTY NOTICES\n\n")
	output.WriteString("Generated by: make notices\n")
	output.WriteString("Do not edit this file manually. Regenerate it after dependency changes.\n\n")
	output.WriteString("SCOPE\n")
	output.WriteString("This notice covers the Go runtime and standard library, every external Go module\n")
	output.WriteString("linked into the supported linux/amd64 or linux/arm64 webdist binary, and every\n")
	output.WriteString("production package in the bundled Web application. Build-only and test-only Web\n")
	output.WriteString("packages are not distributed and are intentionally excluded.\n\n")
	output.WriteString("EXTERNAL RUNTIME: SING-BOX\n")
	output.WriteString("sing-box-panel downloads verified sing-box artifacts directly from the official\n")
	output.WriteString("SagerNet release repository and runs sing-box as a separate process. The current\n")
	output.WriteString("sing-box-panel release artifacts do not copy, link, or bundle the sing-box binary.\n")
	output.WriteString("Upstream: https://github.com/SagerNet/sing-box\n")
	output.WriteString("Copyright: Copyright (C) 2022 by nekohasekai <contact-sagernet@sekai.icu>\n")
	output.WriteString("License: GPL-3.0-or-later (the GPLv3 text is provided in COPYING)\n")
	output.WriteString("Additional upstream term: In addition, no derivative work may use the name or\n")
	output.WriteString("imply association with this application without prior consent.\n\n")
	output.WriteString("INCLUDED COMPONENTS\n\n")
	for _, value := range components {
		fmt.Fprintf(&output, "Component: %s\n", value.Name)
		fmt.Fprintf(&output, "Ecosystem: %s\n", value.Ecosystem)
		fmt.Fprintf(&output, "Version: %s\n", value.Version)
		fmt.Fprintf(&output, "Source: %s\n", value.Source)
		fmt.Fprintf(&output, "License: %s\n", value.LicenseID)
		output.WriteString("License documents:\n")
		for _, file := range value.Files {
			fmt.Fprintf(&output, "  - %s (SHA-256: %s)\n", file.Path, file.Digest)
		}
		output.WriteByte('\n')
	}

	documentList := make([]*licenseDocument, 0, len(documents))
	for _, document := range documents {
		slices.SortFunc(document.Uses, func(left, right documentUse) int {
			if result := strings.Compare(left.Component, right.Component); result != 0 {
				return result
			}
			return strings.Compare(left.Path, right.Path)
		})
		documentList = append(documentList, document)
	}
	slices.SortFunc(documentList, func(left, right *licenseDocument) int {
		return strings.Compare(left.Digest, right.Digest)
	})

	output.WriteString("LICENSE TEXTS\n\n")
	for _, document := range documentList {
		fmt.Fprintf(&output, "================================================================================\n")
		fmt.Fprintf(&output, "SHA-256: %s\n", document.Digest)
		output.WriteString("Applies to:\n")
		for _, use := range document.Uses {
			fmt.Fprintf(&output, "  - %s — %s\n", use.Component, use.Path)
		}
		output.WriteString("--------------------------------------------------------------------------------\n")
		output.Write(document.Content)
		if !bytes.HasSuffix(document.Content, []byte("\n")) {
			output.WriteByte('\n')
		}
		output.WriteByte('\n')
	}
	return output.Bytes(), nil
}

func equalLicenseFiles(left, right []licenseFile) bool {
	return slices.EqualFunc(left, right, func(leftFile, rightFile licenseFile) bool {
		return leftFile.Path == rightFile.Path && leftFile.Digest == rightFile.Digest &&
			bytes.Equal(leftFile.Content, rightFile.Content)
	})
}
