// SPDX-License-Identifier: GPL-3.0-or-later

package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"time"
)

type SubscriptionSourceKind string

const (
	SubscriptionSourceRemote SubscriptionSourceKind = "remote"
	SubscriptionSourceLocal  SubscriptionSourceKind = "local"
)

type SubscriptionSource struct {
	ID               string
	Name             string
	SourceKind       SubscriptionSourceKind
	Config           json.RawMessage
	CurrentVersionID string
	Enabled          bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type SubscriptionSourceSummary struct {
	ID               string
	Name             string
	SourceKind       SubscriptionSourceKind
	HasVersion       bool
	CurrentVersionID string
	Enabled          bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type SubscriptionSourceListFilter struct {
	Cursor *CreatedAtCursor
	Limit  int
}

type SubscriptionSourcePage struct {
	Items []SubscriptionSourceSummary
	Next  *CreatedAtCursor
}

type UpdateSubscriptionSourceInput struct {
	ID                string
	Name              string
	SourceKind        SubscriptionSourceKind
	Config            json.RawMessage
	Enabled           bool
	ExpectedUpdatedAt time.Time
	UpdatedAt         time.Time
}

// SubscriptionToken contains only persisted token metadata and the one-way
// digest. Plaintext tokens are generated by the application and never cross
// this storage boundary.
func (s *Store) CreateSubscriptionSource(
	ctx context.Context,
	source SubscriptionSource,
) (SubscriptionSource, error) {
	prepared, err := prepareNewSubscriptionSource(source)
	if err != nil {
		return SubscriptionSource{}, err
	}
	var stored SubscriptionSource
	err = s.WithTx(ctx, func(tx *sql.Tx) error {
		if err := ensureSourceIdentityAvailable(ctx, tx, prepared.ID, prepared.Name, ""); err != nil {
			return err
		}
		if err := ensureSubscriptionSourceLimits(ctx, tx, "", prepared); err != nil {
			return err
		}
		if _, err := tx.ExecContext(
			ctx,
			`INSERT INTO subscription_sources(
				id, name, source_kind, config_json,
				enabled, created_at, updated_at
			 ) VALUES (?, ?, ?, ?, ?, ?, ?)`,
			prepared.ID,
			prepared.Name,
			string(prepared.SourceKind),
			string(prepared.Config),
			boolInt(prepared.Enabled),
			formatTaskTime(prepared.CreatedAt),
			formatTaskTime(prepared.UpdatedAt),
		); err != nil {
			return fmt.Errorf("insert subscription source: %w", err)
		}
		stored, err = getSubscriptionSource(ctx, tx, prepared.ID)
		return err
	})
	return stored, err
}

func (s *Store) GetSubscriptionSource(
	ctx context.Context,
	sourceID string,
) (SubscriptionSource, error) {
	if err := validateSubscriptionID(sourceID, "source"); err != nil {
		return SubscriptionSource{}, err
	}
	return getSubscriptionSource(ctx, s.db, sourceID)
}

func (s *Store) ListSubscriptionSources(
	ctx context.Context,
	filter SubscriptionSourceListFilter,
) (SubscriptionSourcePage, error) {
	limit, err := normalizePageLimit(filter.Limit)
	if err != nil {
		return SubscriptionSourcePage{}, err
	}
	if err := validateCreatedAtCursor(filter.Cursor); err != nil {
		return SubscriptionSourcePage{}, err
	}
	query := `SELECT id, name, source_kind,
	                  (current_version_id IS NOT NULL),
	                  current_version_id, enabled, created_at, updated_at
             FROM subscription_sources`
	args := make([]any, 0, 4)
	if filter.Cursor != nil {
		query += ` WHERE (created_at < ? OR (created_at = ? AND id < ?))`
		cursorTime := formatTaskTime(filter.Cursor.CreatedAt)
		args = append(args, cursorTime, cursorTime, filter.Cursor.ID)
	}
	query += ` ORDER BY created_at DESC, id DESC LIMIT ?`
	args = append(args, limit+1)
	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return SubscriptionSourcePage{}, fmt.Errorf("list subscription sources: %w", err)
	}
	defer rows.Close()
	items := make([]SubscriptionSourceSummary, 0, limit+1)
	for rows.Next() {
		source, err := scanSubscriptionSourceSummary(rows)
		if err != nil {
			return SubscriptionSourcePage{}, fmt.Errorf("scan subscription source: %w", err)
		}
		items = append(items, source)
	}
	if err := rows.Err(); err != nil {
		return SubscriptionSourcePage{}, fmt.Errorf("iterate subscription sources: %w", err)
	}
	page := SubscriptionSourcePage{Items: items}
	if len(items) > limit {
		page.Items = items[:limit]
		last := page.Items[len(page.Items)-1]
		page.Next = &CreatedAtCursor{CreatedAt: last.CreatedAt, ID: last.ID}
	}
	return page, nil
}

func (s *Store) UpdateSubscriptionSource(
	ctx context.Context,
	input UpdateSubscriptionSourceInput,
) (SubscriptionSource, error) {
	prepared, err := prepareSubscriptionSourceUpdate(input)
	if err != nil {
		return SubscriptionSource{}, err
	}
	var stored SubscriptionSource
	err = s.WithTx(ctx, func(tx *sql.Tx) error {
		current, err := getSubscriptionSource(ctx, tx, prepared.ID)
		if err != nil {
			return err
		}
		if !current.UpdatedAt.Equal(prepared.ExpectedUpdatedAt) {
			return subscriptionConflict("source", prepared.ID, prepared.ExpectedUpdatedAt, current.UpdatedAt)
		}
		if err := ensureSourceIdentityAvailable(ctx, tx, prepared.ID, prepared.Name, prepared.ID); err != nil {
			return err
		}
		if err := ensureSubscriptionSourceLimits(ctx, tx, prepared.ID, SubscriptionSource{
			ID: prepared.ID, Name: prepared.Name, SourceKind: prepared.SourceKind,
			Config: prepared.Config, Enabled: prepared.Enabled,
		}); err != nil {
			return err
		}
		result, err := tx.ExecContext(
			ctx,
			`UPDATE subscription_sources
                SET name = ?, source_kind = ?, config_json = ?, enabled = ?, updated_at = ?
              WHERE id = ? AND updated_at = ?`,
			prepared.Name,
			string(prepared.SourceKind),
			string(prepared.Config),
			boolInt(prepared.Enabled),
			formatTaskTime(prepared.UpdatedAt),
			prepared.ID,
			formatTaskTime(prepared.ExpectedUpdatedAt),
		)
		if err != nil {
			return fmt.Errorf("update subscription source: %w", err)
		}
		if err := requireSingleSubscriptionWrite(result, "update subscription source"); err != nil {
			return err
		}
		stored, err = getSubscriptionSource(ctx, tx, prepared.ID)
		return err
	})
	return stored, err
}

func (s *Store) DeleteSubscriptionSource(
	ctx context.Context,
	sourceID string,
	expectedUpdatedAt time.Time,
) error {
	if err := validateSubscriptionID(sourceID, "source"); err != nil {
		return err
	}
	expectedUpdatedAt, err := requiredUTC(expectedUpdatedAt, "expected source updated_at")
	if err != nil {
		return err
	}
	return s.WithTx(ctx, func(tx *sql.Tx) error {
		current, err := getSubscriptionSource(ctx, tx, sourceID)
		if err != nil {
			return err
		}
		if !current.UpdatedAt.Equal(expectedUpdatedAt) {
			return subscriptionConflict("source", sourceID, expectedUpdatedAt, current.UpdatedAt)
		}
		result, err := tx.ExecContext(
			ctx,
			`DELETE FROM subscription_sources WHERE id = ? AND updated_at = ?`,
			sourceID,
			formatTaskTime(expectedUpdatedAt),
		)
		if err != nil {
			return fmt.Errorf("delete subscription source: %w", err)
		}
		return requireSingleSubscriptionWrite(result, "delete subscription source")
	})
}

func prepareNewSubscriptionSource(source SubscriptionSource) (SubscriptionSource, error) {
	if err := validateSubscriptionID(source.ID, "source"); err != nil {
		return SubscriptionSource{}, err
	}
	if err := validateSubscriptionName(source.Name); err != nil {
		return SubscriptionSource{}, err
	}
	if !validSubscriptionSourceKind(source.SourceKind) {
		return SubscriptionSource{}, fmt.Errorf("invalid subscription source kind %q", source.SourceKind)
	}
	config, err := strictJSONObject(source.Config, maximumSubscriptionConfigBytes, `{}`)
	if err != nil {
		return SubscriptionSource{}, fmt.Errorf("subscription source config: %w", err)
	}
	createdAt := source.CreatedAt
	if createdAt.IsZero() {
		createdAt = time.Now().UTC()
	} else {
		createdAt = createdAt.UTC()
	}
	source.Config = config
	source.CreatedAt = createdAt
	source.UpdatedAt = createdAt
	return source, nil
}

func prepareSubscriptionSourceUpdate(
	input UpdateSubscriptionSourceInput,
) (UpdateSubscriptionSourceInput, error) {
	if err := validateSubscriptionID(input.ID, "source"); err != nil {
		return UpdateSubscriptionSourceInput{}, err
	}
	if err := validateSubscriptionName(input.Name); err != nil {
		return UpdateSubscriptionSourceInput{}, err
	}
	if !validSubscriptionSourceKind(input.SourceKind) {
		return UpdateSubscriptionSourceInput{}, fmt.Errorf("invalid subscription source kind %q", input.SourceKind)
	}
	config, err := strictJSONObject(input.Config, maximumSubscriptionConfigBytes, `{}`)
	if err != nil {
		return UpdateSubscriptionSourceInput{}, fmt.Errorf("subscription source config: %w", err)
	}
	input.ExpectedUpdatedAt, err = requiredUTC(input.ExpectedUpdatedAt, "expected source updated_at")
	if err != nil {
		return UpdateSubscriptionSourceInput{}, err
	}
	input.UpdatedAt, err = nextSubscriptionUpdateTime(input.UpdatedAt, input.ExpectedUpdatedAt)
	if err != nil {
		return UpdateSubscriptionSourceInput{}, err
	}
	input.Config = config
	return input, nil
}

func getSubscriptionSource(ctx context.Context, q queryRower, id string) (SubscriptionSource, error) {
	source, err := scanSubscriptionSource(q.QueryRowContext(
		ctx,
		`SELECT `+subscriptionSourceColumns+` FROM subscription_sources WHERE id = ?`,
		id,
	))
	if errors.Is(err, sql.ErrNoRows) {
		return SubscriptionSource{}, fmt.Errorf("%w: %s", ErrSubscriptionSourceNotFound, id)
	}
	if err != nil {
		return SubscriptionSource{}, fmt.Errorf("get subscription source: %w", err)
	}
	return source, nil
}

func scanSubscriptionSource(row taskScanner) (SubscriptionSource, error) {
	var source SubscriptionSource
	var config, createdAt, updatedAt string
	var currentVersionID sql.NullString
	var enabled int
	if err := row.Scan(
		&source.ID,
		&source.Name,
		&source.SourceKind,
		&config,
		&currentVersionID,
		&enabled,
		&createdAt,
		&updatedAt,
	); err != nil {
		return SubscriptionSource{}, err
	}
	source.Config = append(json.RawMessage(nil), config...)
	if currentVersionID.Valid {
		source.CurrentVersionID = currentVersionID.String
	}
	source.Enabled = enabled != 0
	var err error
	source.CreatedAt, err = parseTaskTime(createdAt)
	if err != nil {
		return SubscriptionSource{}, fmt.Errorf("parse created_at: %w", err)
	}
	source.UpdatedAt, err = parseTaskTime(updatedAt)
	if err != nil {
		return SubscriptionSource{}, fmt.Errorf("parse updated_at: %w", err)
	}
	return source, nil
}

func scanSubscriptionSourceSummary(row taskScanner) (SubscriptionSourceSummary, error) {
	var source SubscriptionSourceSummary
	var hasVersion, enabled int
	var currentVersionID sql.NullString
	var createdAt, updatedAt string
	if err := row.Scan(
		&source.ID,
		&source.Name,
		&source.SourceKind,
		&hasVersion,
		&currentVersionID,
		&enabled,
		&createdAt,
		&updatedAt,
	); err != nil {
		return SubscriptionSourceSummary{}, err
	}
	source.HasVersion = hasVersion != 0
	if currentVersionID.Valid {
		source.CurrentVersionID = currentVersionID.String
	}
	source.Enabled = enabled != 0
	var err error
	source.CreatedAt, err = parseTaskTime(createdAt)
	if err != nil {
		return SubscriptionSourceSummary{}, fmt.Errorf("parse created_at: %w", err)
	}
	source.UpdatedAt, err = parseTaskTime(updatedAt)
	if err != nil {
		return SubscriptionSourceSummary{}, fmt.Errorf("parse updated_at: %w", err)
	}
	return source, nil
}
