// SPDX-License-Identifier: GPL-3.0-or-later

package store

import (
	"bytes"
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"github.com/rehuony/sing-box-panel/internal/jsonstrict"
)

const (
	maximumSubscriptionNameBytes   = 128
	maximumSubscriptionConfigBytes = 64 << 10
	maximumSourceSnapshotBytes     = 4 << 20
	maximumChannelExclusions       = 10_000

	MaximumEnabledSubscriptionChannels       = 256
	MaximumEnabledSubscriptionSources        = 256
	MaximumSubscriptionInputBytes      int64 = 32 << 20
)

var (
	ErrSubscriptionChannelNotFound = errors.New("subscription channel not found")
	ErrSubscriptionChannelExists   = errors.New("subscription channel already exists")
	ErrSubscriptionSourceNotFound  = errors.New("subscription source not found")
	ErrSubscriptionSourceExists    = errors.New("subscription source already exists")
	ErrSubscriptionTokenNotFound   = errors.New("subscription token not found")
	ErrSubscriptionTokenExists     = errors.New("subscription token already exists")
	ErrSubscriptionTokenInactive   = errors.New("subscription token is expired or revoked")
	ErrSubscriptionConflict        = errors.New("subscription resource changed")
	ErrSubscriptionLimitExceeded   = errors.New("subscription resource limit exceeded")
)

// SubscriptionConflictError reports a failed updated_at compare-and-swap.
type SubscriptionConflictError struct {
	Resource string
	ID       string
	Expected time.Time
	Actual   time.Time
}

func (err *SubscriptionConflictError) Error() string {
	return fmt.Sprintf(
		"%v: %s %q expected updated_at %s, actual %s",
		ErrSubscriptionConflict,
		err.Resource,
		err.ID,
		err.Expected.UTC().Format(time.RFC3339Nano),
		err.Actual.UTC().Format(time.RFC3339Nano),
	)
}

func (err *SubscriptionConflictError) Unwrap() error { return ErrSubscriptionConflict }

// SubscriptionFormat identifies one renderer contract.
type SubscriptionFormat string

const (
	SubscriptionFormatSingBox SubscriptionFormat = "sing-box"
	SubscriptionFormatMihomo  SubscriptionFormat = "mihomo"
	SubscriptionFormatLoon    SubscriptionFormat = "loon"
)

// SubscriptionChannelConfig is the strict, renderer-owned channel policy.
type SubscriptionChannelConfig struct {
	ExcludeTags  []string `json:"exclude_tags,omitempty"`
	ExcludeTypes []string `json:"exclude_types,omitempty"`
}

type SubscriptionChannel struct {
	ID        string
	Name      string
	Format    SubscriptionFormat
	Config    json.RawMessage
	Enabled   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SubscriptionChannelSummary struct {
	ID        string
	Name      string
	Format    SubscriptionFormat
	Enabled   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SubscriptionChannelListFilter struct {
	Cursor *CreatedAtCursor
	Limit  int
}

type SubscriptionChannelPage struct {
	Items []SubscriptionChannelSummary
	Next  *CreatedAtCursor
}

type UpdateSubscriptionChannelInput struct {
	ID                string
	Name              string
	Format            SubscriptionFormat
	Config            json.RawMessage
	Enabled           bool
	ExpectedUpdatedAt time.Time
	UpdatedAt         time.Time
}

type SubscriptionSourceKind string

const (
	SubscriptionSourceRemote SubscriptionSourceKind = "remote"
	SubscriptionSourceLocal  SubscriptionSourceKind = "local"
)

type SubscriptionSource struct {
	ID             string
	Name           string
	SourceKind     SubscriptionSourceKind
	Config         json.RawMessage
	LatestSnapshot json.RawMessage
	Enabled        bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type SubscriptionSourceSummary struct {
	ID          string
	Name        string
	SourceKind  SubscriptionSourceKind
	HasSnapshot bool
	Enabled     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SubscriptionSourceListFilter struct {
	Cursor *CreatedAtCursor
	Limit  int
}

type SubscriptionSourcePage struct {
	Items []SubscriptionSourceSummary
	Next  *CreatedAtCursor
}

type UpdateSubscriptionSourceInput struct {
	ID                string
	Name              string
	SourceKind        SubscriptionSourceKind
	Config            json.RawMessage
	Enabled           bool
	ExpectedUpdatedAt time.Time
	UpdatedAt         time.Time
}

type UpdateSubscriptionSourceSnapshotInput struct {
	ID                string
	LatestSnapshot    json.RawMessage
	ExpectedUpdatedAt time.Time
	UpdatedAt         time.Time
}

// SubscriptionToken contains only persisted token metadata and the one-way
// digest. Plaintext tokens are generated by the application and never cross
// this storage boundary.
type SubscriptionToken struct {
	ID          string
	TokenSHA256 string
	ExpiresAt   *time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

// Active reports whether a token is usable at the supplied instant. Expiry is
// exclusive: a token is inactive when at is equal to expires_at.
func (token SubscriptionToken) Active(at time.Time) bool {
	if token.RevokedAt != nil {
		return false
	}
	return token.ExpiresAt == nil || at.UTC().Before(token.ExpiresAt.UTC())
}

type SubscriptionTokenRotation struct {
	Revoked SubscriptionToken
	Created SubscriptionToken
}

type SubscriptionTokenListFilter struct {
	Cursor *CreatedAtCursor
	Limit  int
}

type SubscriptionTokenPage struct {
	Items []SubscriptionToken
	Next  *CreatedAtCursor
}

const subscriptionChannelColumns = `
    id, name, format, config_json, enabled, created_at, updated_at`

const subscriptionSourceColumns = `
    id, name, source_kind, config_json, latest_snapshot_json, enabled,
    created_at, updated_at`

const subscriptionTokenColumns = `
    id, token_sha256, expires_at, revoked_at, created_at`

func (s *Store) CreateSubscriptionChannel(
	ctx context.Context,
	channel SubscriptionChannel,
) (SubscriptionChannel, error) {
	prepared, err := prepareNewSubscriptionChannel(channel)
	if err != nil {
		return SubscriptionChannel{}, err
	}
	var stored SubscriptionChannel
	err = s.WithTx(ctx, func(tx *sql.Tx) error {
		if err := ensureChannelIdentityAvailable(ctx, tx, prepared.ID, prepared.Name, ""); err != nil {
			return err
		}
		if err := ensureSubscriptionChannelLimits(ctx, tx, "", prepared); err != nil {
			return err
		}
		if _, err := tx.ExecContext(
			ctx,
			`INSERT INTO subscription_channels(
                id, name, format, config_json, enabled, created_at, updated_at
             ) VALUES (?, ?, ?, ?, ?, ?, ?)`,
			prepared.ID,
			prepared.Name,
			string(prepared.Format),
			string(prepared.Config),
			boolInt(prepared.Enabled),
			formatTaskTime(prepared.CreatedAt),
			formatTaskTime(prepared.UpdatedAt),
		); err != nil {
			return fmt.Errorf("insert subscription channel: %w", err)
		}
		stored, err = getSubscriptionChannel(ctx, tx, prepared.ID)
		return err
	})
	return stored, err
}

func (s *Store) GetSubscriptionChannel(
	ctx context.Context,
	channelID string,
) (SubscriptionChannel, error) {
	if err := validateSubscriptionID(channelID, "channel"); err != nil {
		return SubscriptionChannel{}, err
	}
	return getSubscriptionChannel(ctx, s.db, channelID)
}

func (s *Store) ListSubscriptionChannels(
	ctx context.Context,
	filter SubscriptionChannelListFilter,
) (SubscriptionChannelPage, error) {
	limit, err := normalizePageLimit(filter.Limit)
	if err != nil {
		return SubscriptionChannelPage{}, err
	}
	if err := validateCreatedAtCursor(filter.Cursor); err != nil {
		return SubscriptionChannelPage{}, err
	}
	query := `SELECT id, name, format, enabled, created_at, updated_at
           FROM subscription_channels`
	args := make([]any, 0, 4)
	if filter.Cursor != nil {
		query += ` WHERE (created_at < ? OR (created_at = ? AND id < ?))`
		cursorTime := formatTaskTime(filter.Cursor.CreatedAt)
		args = append(args, cursorTime, cursorTime, filter.Cursor.ID)
	}
	query += ` ORDER BY created_at DESC, id DESC LIMIT ?`
	args = append(args, limit+1)
	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return SubscriptionChannelPage{}, fmt.Errorf("list subscription channels: %w", err)
	}
	defer rows.Close()
	items := make([]SubscriptionChannelSummary, 0, limit+1)
	for rows.Next() {
		channel, err := scanSubscriptionChannelSummary(rows)
		if err != nil {
			return SubscriptionChannelPage{}, fmt.Errorf("scan subscription channel: %w", err)
		}
		items = append(items, channel)
	}
	if err := rows.Err(); err != nil {
		return SubscriptionChannelPage{}, fmt.Errorf("iterate subscription channels: %w", err)
	}
	page := SubscriptionChannelPage{Items: items}
	if len(items) > limit {
		page.Items = items[:limit]
		last := page.Items[len(page.Items)-1]
		page.Next = &CreatedAtCursor{CreatedAt: last.CreatedAt, ID: last.ID}
	}
	return page, nil
}

func (s *Store) UpdateSubscriptionChannel(
	ctx context.Context,
	input UpdateSubscriptionChannelInput,
) (SubscriptionChannel, error) {
	prepared, err := prepareSubscriptionChannelUpdate(input)
	if err != nil {
		return SubscriptionChannel{}, err
	}
	var stored SubscriptionChannel
	err = s.WithTx(ctx, func(tx *sql.Tx) error {
		current, err := getSubscriptionChannel(ctx, tx, prepared.ID)
		if err != nil {
			return err
		}
		if !current.UpdatedAt.Equal(prepared.ExpectedUpdatedAt) {
			return subscriptionConflict("channel", prepared.ID, prepared.ExpectedUpdatedAt, current.UpdatedAt)
		}
		if err := ensureChannelIdentityAvailable(ctx, tx, prepared.ID, prepared.Name, prepared.ID); err != nil {
			return err
		}
		if err := ensureSubscriptionChannelLimits(ctx, tx, prepared.ID, SubscriptionChannel{
			ID: prepared.ID, Name: prepared.Name, Format: prepared.Format,
			Config: prepared.Config, Enabled: prepared.Enabled,
		}); err != nil {
			return err
		}
		result, err := tx.ExecContext(
			ctx,
			`UPDATE subscription_channels
                SET name = ?, format = ?, config_json = ?, enabled = ?, updated_at = ?
              WHERE id = ? AND updated_at = ?`,
			prepared.Name,
			string(prepared.Format),
			string(prepared.Config),
			boolInt(prepared.Enabled),
			formatTaskTime(prepared.UpdatedAt),
			prepared.ID,
			formatTaskTime(prepared.ExpectedUpdatedAt),
		)
		if err != nil {
			return fmt.Errorf("update subscription channel: %w", err)
		}
		if err := requireSingleSubscriptionWrite(result, "update subscription channel"); err != nil {
			return err
		}
		stored, err = getSubscriptionChannel(ctx, tx, prepared.ID)
		return err
	})
	return stored, err
}

func (s *Store) DeleteSubscriptionChannel(
	ctx context.Context,
	channelID string,
	expectedUpdatedAt time.Time,
) error {
	if err := validateSubscriptionID(channelID, "channel"); err != nil {
		return err
	}
	expectedUpdatedAt, err := requiredUTC(expectedUpdatedAt, "expected channel updated_at")
	if err != nil {
		return err
	}
	return s.WithTx(ctx, func(tx *sql.Tx) error {
		current, err := getSubscriptionChannel(ctx, tx, channelID)
		if err != nil {
			return err
		}
		if !current.UpdatedAt.Equal(expectedUpdatedAt) {
			return subscriptionConflict("channel", channelID, expectedUpdatedAt, current.UpdatedAt)
		}
		result, err := tx.ExecContext(
			ctx,
			`DELETE FROM subscription_channels WHERE id = ? AND updated_at = ?`,
			channelID,
			formatTaskTime(expectedUpdatedAt),
		)
		if err != nil {
			return fmt.Errorf("delete subscription channel: %w", err)
		}
		return requireSingleSubscriptionWrite(result, "delete subscription channel")
	})
}

func (s *Store) CreateSubscriptionSource(
	ctx context.Context,
	source SubscriptionSource,
) (SubscriptionSource, error) {
	prepared, err := prepareNewSubscriptionSource(source)
	if err != nil {
		return SubscriptionSource{}, err
	}
	var stored SubscriptionSource
	err = s.WithTx(ctx, func(tx *sql.Tx) error {
		if err := ensureSourceIdentityAvailable(ctx, tx, prepared.ID, prepared.Name, ""); err != nil {
			return err
		}
		if err := ensureSubscriptionSourceLimits(ctx, tx, "", prepared); err != nil {
			return err
		}
		if _, err := tx.ExecContext(
			ctx,
			`INSERT INTO subscription_sources(
                id, name, source_kind, config_json, latest_snapshot_json,
                enabled, created_at, updated_at
             ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
			prepared.ID,
			prepared.Name,
			string(prepared.SourceKind),
			string(prepared.Config),
			nullableRawJSON(prepared.LatestSnapshot),
			boolInt(prepared.Enabled),
			formatTaskTime(prepared.CreatedAt),
			formatTaskTime(prepared.UpdatedAt),
		); err != nil {
			return fmt.Errorf("insert subscription source: %w", err)
		}
		stored, err = getSubscriptionSource(ctx, tx, prepared.ID)
		return err
	})
	return stored, err
}

func (s *Store) GetSubscriptionSource(
	ctx context.Context,
	sourceID string,
) (SubscriptionSource, error) {
	if err := validateSubscriptionID(sourceID, "source"); err != nil {
		return SubscriptionSource{}, err
	}
	return getSubscriptionSource(ctx, s.db, sourceID)
}

func (s *Store) ListSubscriptionSources(
	ctx context.Context,
	filter SubscriptionSourceListFilter,
) (SubscriptionSourcePage, error) {
	limit, err := normalizePageLimit(filter.Limit)
	if err != nil {
		return SubscriptionSourcePage{}, err
	}
	if err := validateCreatedAtCursor(filter.Cursor); err != nil {
		return SubscriptionSourcePage{}, err
	}
	query := `SELECT id, name, source_kind, latest_snapshot_json IS NOT NULL,
                  enabled, created_at, updated_at
             FROM subscription_sources`
	args := make([]any, 0, 4)
	if filter.Cursor != nil {
		query += ` WHERE (created_at < ? OR (created_at = ? AND id < ?))`
		cursorTime := formatTaskTime(filter.Cursor.CreatedAt)
		args = append(args, cursorTime, cursorTime, filter.Cursor.ID)
	}
	query += ` ORDER BY created_at DESC, id DESC LIMIT ?`
	args = append(args, limit+1)
	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return SubscriptionSourcePage{}, fmt.Errorf("list subscription sources: %w", err)
	}
	defer rows.Close()
	items := make([]SubscriptionSourceSummary, 0, limit+1)
	for rows.Next() {
		source, err := scanSubscriptionSourceSummary(rows)
		if err != nil {
			return SubscriptionSourcePage{}, fmt.Errorf("scan subscription source: %w", err)
		}
		items = append(items, source)
	}
	if err := rows.Err(); err != nil {
		return SubscriptionSourcePage{}, fmt.Errorf("iterate subscription sources: %w", err)
	}
	page := SubscriptionSourcePage{Items: items}
	if len(items) > limit {
		page.Items = items[:limit]
		last := page.Items[len(page.Items)-1]
		page.Next = &CreatedAtCursor{CreatedAt: last.CreatedAt, ID: last.ID}
	}
	return page, nil
}

func (s *Store) UpdateSubscriptionSource(
	ctx context.Context,
	input UpdateSubscriptionSourceInput,
) (SubscriptionSource, error) {
	prepared, err := prepareSubscriptionSourceUpdate(input)
	if err != nil {
		return SubscriptionSource{}, err
	}
	var stored SubscriptionSource
	err = s.WithTx(ctx, func(tx *sql.Tx) error {
		current, err := getSubscriptionSource(ctx, tx, prepared.ID)
		if err != nil {
			return err
		}
		if !current.UpdatedAt.Equal(prepared.ExpectedUpdatedAt) {
			return subscriptionConflict("source", prepared.ID, prepared.ExpectedUpdatedAt, current.UpdatedAt)
		}
		if err := ensureSourceIdentityAvailable(ctx, tx, prepared.ID, prepared.Name, prepared.ID); err != nil {
			return err
		}
		if err := ensureSubscriptionSourceLimits(ctx, tx, prepared.ID, SubscriptionSource{
			ID: prepared.ID, Name: prepared.Name, SourceKind: prepared.SourceKind,
			Config: prepared.Config, LatestSnapshot: current.LatestSnapshot, Enabled: prepared.Enabled,
		}); err != nil {
			return err
		}
		result, err := tx.ExecContext(
			ctx,
			`UPDATE subscription_sources
                SET name = ?, source_kind = ?, config_json = ?, enabled = ?, updated_at = ?
              WHERE id = ? AND updated_at = ?`,
			prepared.Name,
			string(prepared.SourceKind),
			string(prepared.Config),
			boolInt(prepared.Enabled),
			formatTaskTime(prepared.UpdatedAt),
			prepared.ID,
			formatTaskTime(prepared.ExpectedUpdatedAt),
		)
		if err != nil {
			return fmt.Errorf("update subscription source: %w", err)
		}
		if err := requireSingleSubscriptionWrite(result, "update subscription source"); err != nil {
			return err
		}
		stored, err = getSubscriptionSource(ctx, tx, prepared.ID)
		return err
	})
	return stored, err
}

func (s *Store) UpdateSubscriptionSourceSnapshot(
	ctx context.Context,
	input UpdateSubscriptionSourceSnapshotInput,
) (SubscriptionSource, error) {
	if err := validateSubscriptionID(input.ID, "source"); err != nil {
		return SubscriptionSource{}, err
	}
	expected, err := requiredUTC(input.ExpectedUpdatedAt, "expected source updated_at")
	if err != nil {
		return SubscriptionSource{}, err
	}
	updated, err := nextSubscriptionUpdateTime(input.UpdatedAt, expected)
	if err != nil {
		return SubscriptionSource{}, err
	}
	snapshot, err := strictSourceSnapshot(input.LatestSnapshot)
	if err != nil {
		return SubscriptionSource{}, err
	}
	var stored SubscriptionSource
	err = s.WithTx(ctx, func(tx *sql.Tx) error {
		current, err := getSubscriptionSource(ctx, tx, input.ID)
		if err != nil {
			return err
		}
		if !current.UpdatedAt.Equal(expected) {
			return subscriptionConflict("source", input.ID, expected, current.UpdatedAt)
		}
		if err := ensureSubscriptionSourceLimits(ctx, tx, input.ID, SubscriptionSource{
			ID: current.ID, Name: current.Name, SourceKind: current.SourceKind,
			Config: current.Config, LatestSnapshot: snapshot, Enabled: current.Enabled,
		}); err != nil {
			return err
		}
		result, err := tx.ExecContext(
			ctx,
			`UPDATE subscription_sources
                SET latest_snapshot_json = ?, updated_at = ?
              WHERE id = ? AND updated_at = ?`,
			string(snapshot),
			formatTaskTime(updated),
			input.ID,
			formatTaskTime(expected),
		)
		if err != nil {
			return fmt.Errorf("update subscription source snapshot: %w", err)
		}
		if err := requireSingleSubscriptionWrite(result, "update subscription source snapshot"); err != nil {
			return err
		}
		stored, err = getSubscriptionSource(ctx, tx, input.ID)
		return err
	})
	return stored, err
}

func (s *Store) DeleteSubscriptionSource(
	ctx context.Context,
	sourceID string,
	expectedUpdatedAt time.Time,
) error {
	if err := validateSubscriptionID(sourceID, "source"); err != nil {
		return err
	}
	expectedUpdatedAt, err := requiredUTC(expectedUpdatedAt, "expected source updated_at")
	if err != nil {
		return err
	}
	return s.WithTx(ctx, func(tx *sql.Tx) error {
		current, err := getSubscriptionSource(ctx, tx, sourceID)
		if err != nil {
			return err
		}
		if !current.UpdatedAt.Equal(expectedUpdatedAt) {
			return subscriptionConflict("source", sourceID, expectedUpdatedAt, current.UpdatedAt)
		}
		result, err := tx.ExecContext(
			ctx,
			`DELETE FROM subscription_sources WHERE id = ? AND updated_at = ?`,
			sourceID,
			formatTaskTime(expectedUpdatedAt),
		)
		if err != nil {
			return fmt.Errorf("delete subscription source: %w", err)
		}
		return requireSingleSubscriptionWrite(result, "delete subscription source")
	})
}

func (s *Store) CreateSubscriptionToken(
	ctx context.Context,
	token SubscriptionToken,
) (SubscriptionToken, error) {
	prepared, err := prepareNewSubscriptionToken(token)
	if err != nil {
		return SubscriptionToken{}, err
	}
	var stored SubscriptionToken
	err = s.WithTx(ctx, func(tx *sql.Tx) error {
		if err := ensureTokenIdentityAvailable(ctx, tx, prepared.ID, prepared.TokenSHA256); err != nil {
			return err
		}
		if err := insertSubscriptionToken(ctx, tx, prepared); err != nil {
			return err
		}
		stored, err = getSubscriptionToken(ctx, tx, prepared.ID)
		return err
	})
	return stored, err
}

func (s *Store) GetSubscriptionToken(
	ctx context.Context,
	tokenID string,
) (SubscriptionToken, error) {
	if err := validateSubscriptionID(tokenID, "token"); err != nil {
		return SubscriptionToken{}, err
	}
	return getSubscriptionToken(ctx, s.db, tokenID)
}

func (s *Store) ListSubscriptionTokens(
	ctx context.Context,
	filter SubscriptionTokenListFilter,
) (SubscriptionTokenPage, error) {
	limit, err := normalizePageLimit(filter.Limit)
	if err != nil {
		return SubscriptionTokenPage{}, err
	}
	if err := validateCreatedAtCursor(filter.Cursor); err != nil {
		return SubscriptionTokenPage{}, err
	}
	query := `SELECT ` + subscriptionTokenColumns + ` FROM subscription_tokens`
	args := make([]any, 0, 4)
	if filter.Cursor != nil {
		query += ` WHERE (created_at < ? OR (created_at = ? AND id < ?))`
		cursorTime := formatTaskTime(filter.Cursor.CreatedAt)
		args = append(args, cursorTime, cursorTime, filter.Cursor.ID)
	}
	query += ` ORDER BY created_at DESC, id DESC LIMIT ?`
	args = append(args, limit+1)
	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return SubscriptionTokenPage{}, fmt.Errorf("list subscription tokens: %w", err)
	}
	defer rows.Close()
	items := make([]SubscriptionToken, 0, limit+1)
	for rows.Next() {
		token, err := scanSubscriptionToken(rows)
		if err != nil {
			return SubscriptionTokenPage{}, fmt.Errorf("scan subscription token: %w", err)
		}
		items = append(items, token)
	}
	if err := rows.Err(); err != nil {
		return SubscriptionTokenPage{}, fmt.Errorf("iterate subscription tokens: %w", err)
	}
	page := SubscriptionTokenPage{Items: items}
	if len(items) > limit {
		page.Items = items[:limit]
		last := page.Items[len(page.Items)-1]
		page.Next = &CreatedAtCursor{CreatedAt: last.CreatedAt, ID: last.ID}
	}
	return page, nil
}

// FindActiveSubscriptionToken resolves a one-way digest and applies immediate
// revoke/expiry policy. Callers should present the same public error for not
// found and inactive tokens.
func (s *Store) FindActiveSubscriptionToken(
	ctx context.Context,
	tokenSHA256 string,
	at time.Time,
) (SubscriptionToken, error) {
	digest, err := normalizeTokenDigest(tokenSHA256)
	if err != nil {
		return SubscriptionToken{}, err
	}
	at, err = requiredUTC(at, "token validation time")
	if err != nil {
		return SubscriptionToken{}, err
	}
	token, err := scanSubscriptionToken(s.db.QueryRowContext(
		ctx,
		`SELECT `+subscriptionTokenColumns+`
           FROM subscription_tokens WHERE token_sha256 = ?`,
		digest,
	))
	if errors.Is(err, sql.ErrNoRows) {
		return SubscriptionToken{}, ErrSubscriptionTokenNotFound
	}
	if err != nil {
		return SubscriptionToken{}, fmt.Errorf("find subscription token: %w", err)
	}
	if !token.Active(at) {
		return SubscriptionToken{}, fmt.Errorf("%w: %s", ErrSubscriptionTokenInactive, token.ID)
	}
	return token, nil
}

// RotateSubscriptionToken atomically revokes the old active token and inserts
// its replacement.
func (s *Store) RotateSubscriptionToken(
	ctx context.Context,
	oldTokenID string,
	replacement SubscriptionToken,
	rotatedAt time.Time,
) (SubscriptionTokenRotation, error) {
	if err := validateSubscriptionID(oldTokenID, "token"); err != nil {
		return SubscriptionTokenRotation{}, err
	}
	rotatedAt, err := requiredUTC(rotatedAt, "token rotation time")
	if err != nil {
		return SubscriptionTokenRotation{}, err
	}
	replacement.CreatedAt = rotatedAt
	prepared, err := prepareNewSubscriptionToken(replacement)
	if err != nil {
		return SubscriptionTokenRotation{}, err
	}
	var rotation SubscriptionTokenRotation
	err = s.WithTx(ctx, func(tx *sql.Tx) error {
		current, err := getSubscriptionToken(ctx, tx, oldTokenID)
		if err != nil {
			return err
		}
		if !current.Active(rotatedAt) {
			return fmt.Errorf("%w: %s", ErrSubscriptionTokenInactive, current.ID)
		}
		if err := ensureTokenIdentityAvailable(ctx, tx, prepared.ID, prepared.TokenSHA256); err != nil {
			return err
		}
		result, err := tx.ExecContext(
			ctx,
			`UPDATE subscription_tokens
                SET revoked_at = ?
              WHERE id = ? AND revoked_at IS NULL`,
			formatTaskTime(rotatedAt),
			oldTokenID,
		)
		if err != nil {
			return fmt.Errorf("revoke rotated subscription token: %w", err)
		}
		if err := requireSingleSubscriptionWrite(result, "revoke rotated subscription token"); err != nil {
			return err
		}
		if err := insertSubscriptionToken(ctx, tx, prepared); err != nil {
			return err
		}
		rotation.Revoked, err = getSubscriptionToken(ctx, tx, oldTokenID)
		if err != nil {
			return err
		}
		rotation.Created, err = getSubscriptionToken(ctx, tx, prepared.ID)
		return err
	})
	return rotation, err
}

func (s *Store) RevokeSubscriptionToken(
	ctx context.Context,
	tokenID string,
	revokedAt time.Time,
) (SubscriptionToken, error) {
	if err := validateSubscriptionID(tokenID, "token"); err != nil {
		return SubscriptionToken{}, err
	}
	revokedAt, err := requiredUTC(revokedAt, "token revocation time")
	if err != nil {
		return SubscriptionToken{}, err
	}
	var stored SubscriptionToken
	err = s.WithTx(ctx, func(tx *sql.Tx) error {
		current, err := getSubscriptionToken(ctx, tx, tokenID)
		if err != nil {
			return err
		}
		if current.RevokedAt != nil {
			stored = current
			return nil
		}
		if revokedAt.Before(current.CreatedAt) {
			return errors.New("token revocation time precedes creation")
		}
		result, err := tx.ExecContext(
			ctx,
			`UPDATE subscription_tokens SET revoked_at = ? WHERE id = ? AND revoked_at IS NULL`,
			formatTaskTime(revokedAt),
			tokenID,
		)
		if err != nil {
			return fmt.Errorf("revoke subscription token: %w", err)
		}
		if err := requireSingleSubscriptionWrite(result, "revoke subscription token"); err != nil {
			return err
		}
		stored, err = getSubscriptionToken(ctx, tx, tokenID)
		return err
	})
	return stored, err
}

// DecodeSubscriptionChannelConfig validates and returns the normalized channel
// policy used by application preview rendering.
func DecodeSubscriptionChannelConfig(raw json.RawMessage) (SubscriptionChannelConfig, error) {
	if len(raw) == 0 {
		raw = json.RawMessage(`{}`)
	}
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) == 0 || trimmed[0] != '{' {
		return SubscriptionChannelConfig{}, errors.New("subscription channel config must be a non-null JSON object")
	}
	var config SubscriptionChannelConfig
	if err := jsonstrict.Decode(raw, maximumSubscriptionConfigBytes, &config); err != nil {
		return SubscriptionChannelConfig{}, fmt.Errorf("subscription channel config: %w", err)
	}
	var fields map[string]json.RawMessage
	if err := jsonstrict.Decode(raw, maximumSubscriptionConfigBytes, &fields); err != nil || fields == nil {
		return SubscriptionChannelConfig{}, errors.New("subscription channel config must be a non-null JSON object")
	}
	for name, value := range fields {
		if bytes.Equal(bytes.TrimSpace(value), []byte("null")) {
			return SubscriptionChannelConfig{}, fmt.Errorf("subscription channel config field %q cannot be null", name)
		}
	}
	if config.ExcludeTags == nil {
		config.ExcludeTags = []string{}
	}
	if config.ExcludeTypes == nil {
		config.ExcludeTypes = []string{}
	}
	if len(config.ExcludeTags) > maximumChannelExclusions || len(config.ExcludeTypes) > maximumChannelExclusions {
		return SubscriptionChannelConfig{}, errors.New("subscription channel config has too many exclusions")
	}
	if err := validateUniqueSubscriptionStrings(config.ExcludeTags, validSubscriptionTag, "tag"); err != nil {
		return SubscriptionChannelConfig{}, err
	}
	if err := validateUniqueSubscriptionStrings(config.ExcludeTypes, validSubscriptionType, "type"); err != nil {
		return SubscriptionChannelConfig{}, err
	}
	return config, nil
}

func prepareNewSubscriptionChannel(channel SubscriptionChannel) (SubscriptionChannel, error) {
	if err := validateSubscriptionID(channel.ID, "channel"); err != nil {
		return SubscriptionChannel{}, err
	}
	if err := validateSubscriptionName(channel.Name); err != nil {
		return SubscriptionChannel{}, err
	}
	if !validSubscriptionFormat(channel.Format) {
		return SubscriptionChannel{}, fmt.Errorf("invalid subscription format %q", channel.Format)
	}
	config, err := canonicalChannelConfig(channel.Config)
	if err != nil {
		return SubscriptionChannel{}, err
	}
	createdAt := channel.CreatedAt
	if createdAt.IsZero() {
		createdAt = time.Now().UTC()
	} else {
		createdAt = createdAt.UTC()
	}
	channel.Config = config
	channel.CreatedAt = createdAt
	channel.UpdatedAt = createdAt
	return channel, nil
}

func prepareSubscriptionChannelUpdate(
	input UpdateSubscriptionChannelInput,
) (UpdateSubscriptionChannelInput, error) {
	if err := validateSubscriptionID(input.ID, "channel"); err != nil {
		return UpdateSubscriptionChannelInput{}, err
	}
	if err := validateSubscriptionName(input.Name); err != nil {
		return UpdateSubscriptionChannelInput{}, err
	}
	if !validSubscriptionFormat(input.Format) {
		return UpdateSubscriptionChannelInput{}, fmt.Errorf("invalid subscription format %q", input.Format)
	}
	config, err := canonicalChannelConfig(input.Config)
	if err != nil {
		return UpdateSubscriptionChannelInput{}, err
	}
	input.ExpectedUpdatedAt, err = requiredUTC(input.ExpectedUpdatedAt, "expected channel updated_at")
	if err != nil {
		return UpdateSubscriptionChannelInput{}, err
	}
	input.UpdatedAt, err = nextSubscriptionUpdateTime(input.UpdatedAt, input.ExpectedUpdatedAt)
	if err != nil {
		return UpdateSubscriptionChannelInput{}, err
	}
	input.Config = config
	return input, nil
}

func prepareNewSubscriptionSource(source SubscriptionSource) (SubscriptionSource, error) {
	if err := validateSubscriptionID(source.ID, "source"); err != nil {
		return SubscriptionSource{}, err
	}
	if err := validateSubscriptionName(source.Name); err != nil {
		return SubscriptionSource{}, err
	}
	if !validSubscriptionSourceKind(source.SourceKind) {
		return SubscriptionSource{}, fmt.Errorf("invalid subscription source kind %q", source.SourceKind)
	}
	config, err := strictJSONObject(source.Config, maximumSubscriptionConfigBytes, `{}`)
	if err != nil {
		return SubscriptionSource{}, fmt.Errorf("subscription source config: %w", err)
	}
	var snapshot json.RawMessage
	if len(source.LatestSnapshot) != 0 {
		snapshot, err = strictSourceSnapshot(source.LatestSnapshot)
		if err != nil {
			return SubscriptionSource{}, err
		}
	}
	createdAt := source.CreatedAt
	if createdAt.IsZero() {
		createdAt = time.Now().UTC()
	} else {
		createdAt = createdAt.UTC()
	}
	source.Config = config
	source.LatestSnapshot = snapshot
	source.CreatedAt = createdAt
	source.UpdatedAt = createdAt
	return source, nil
}

func prepareSubscriptionSourceUpdate(
	input UpdateSubscriptionSourceInput,
) (UpdateSubscriptionSourceInput, error) {
	if err := validateSubscriptionID(input.ID, "source"); err != nil {
		return UpdateSubscriptionSourceInput{}, err
	}
	if err := validateSubscriptionName(input.Name); err != nil {
		return UpdateSubscriptionSourceInput{}, err
	}
	if !validSubscriptionSourceKind(input.SourceKind) {
		return UpdateSubscriptionSourceInput{}, fmt.Errorf("invalid subscription source kind %q", input.SourceKind)
	}
	config, err := strictJSONObject(input.Config, maximumSubscriptionConfigBytes, `{}`)
	if err != nil {
		return UpdateSubscriptionSourceInput{}, fmt.Errorf("subscription source config: %w", err)
	}
	input.ExpectedUpdatedAt, err = requiredUTC(input.ExpectedUpdatedAt, "expected source updated_at")
	if err != nil {
		return UpdateSubscriptionSourceInput{}, err
	}
	input.UpdatedAt, err = nextSubscriptionUpdateTime(input.UpdatedAt, input.ExpectedUpdatedAt)
	if err != nil {
		return UpdateSubscriptionSourceInput{}, err
	}
	input.Config = config
	return input, nil
}

func prepareNewSubscriptionToken(token SubscriptionToken) (SubscriptionToken, error) {
	if err := validateSubscriptionID(token.ID, "token"); err != nil {
		return SubscriptionToken{}, err
	}
	digest, err := normalizeTokenDigest(token.TokenSHA256)
	if err != nil {
		return SubscriptionToken{}, err
	}
	createdAt := token.CreatedAt
	if createdAt.IsZero() {
		createdAt = time.Now().UTC()
	} else {
		createdAt = createdAt.UTC()
	}
	if token.ExpiresAt != nil {
		expiresAt := token.ExpiresAt.UTC()
		if !expiresAt.After(createdAt) {
			return SubscriptionToken{}, errors.New("subscription token expiry must follow creation")
		}
		token.ExpiresAt = &expiresAt
	}
	if token.RevokedAt != nil {
		return SubscriptionToken{}, errors.New("new subscription token cannot be revoked")
	}
	token.TokenSHA256 = digest
	token.CreatedAt = createdAt
	return token, nil
}

func canonicalChannelConfig(raw json.RawMessage) (json.RawMessage, error) {
	config, err := DecodeSubscriptionChannelConfig(raw)
	if err != nil {
		return nil, err
	}
	encoded, err := json.Marshal(config)
	if err != nil {
		return nil, fmt.Errorf("encode subscription channel config: %w", err)
	}
	return encoded, nil
}

func strictJSONObject(raw json.RawMessage, maximum int64, fallback string) (json.RawMessage, error) {
	if len(raw) == 0 {
		raw = json.RawMessage(fallback)
	}
	var value map[string]any
	if err := jsonstrict.Decode(raw, maximum, &value); err != nil {
		return nil, err
	}
	if value == nil {
		return nil, errors.New("value must be a non-null JSON object")
	}
	encoded, err := json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("encode JSON object: %w", err)
	}
	return bytes.Clone(encoded), nil
}

func strictSourceSnapshot(raw json.RawMessage) (json.RawMessage, error) {
	if len(raw) == 0 {
		return nil, errors.New("subscription source snapshot is empty")
	}
	var value any
	if err := jsonstrict.Decode(raw, maximumSourceSnapshotBytes, &value); err != nil {
		return nil, fmt.Errorf("subscription source snapshot: %w", err)
	}
	switch value.(type) {
	case map[string]any, []any:
	default:
		return nil, errors.New("subscription source snapshot must be a JSON object or array")
	}
	encoded, err := json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("encode subscription source snapshot: %w", err)
	}
	return bytes.Clone(encoded), nil
}

func ensureSubscriptionChannelLimits(
	ctx context.Context,
	q queryRower,
	excludeID string,
	candidate SubscriptionChannel,
) error {
	if !candidate.Enabled {
		return nil
	}
	var enabled int64
	if err := q.QueryRowContext(
		ctx,
		`SELECT count(*) FROM subscription_channels WHERE enabled = 1 AND id <> ?`,
		excludeID,
	).Scan(&enabled); err != nil {
		return fmt.Errorf("count enabled subscription channels: %w", err)
	}
	if enabled >= MaximumEnabledSubscriptionChannels {
		return fmt.Errorf("%w: enabled channel count exceeds %d", ErrSubscriptionLimitExceeded, MaximumEnabledSubscriptionChannels)
	}
	return ensureSubscriptionInputBudget(ctx, q, excludeID, "", int64(len(candidate.Config)))
}

func ensureSubscriptionSourceLimits(
	ctx context.Context,
	q queryRower,
	excludeID string,
	candidate SubscriptionSource,
) error {
	if !candidate.Enabled {
		return nil
	}
	var enabled int64
	if err := q.QueryRowContext(
		ctx,
		`SELECT count(*) FROM subscription_sources WHERE enabled = 1 AND id <> ?`,
		excludeID,
	).Scan(&enabled); err != nil {
		return fmt.Errorf("count enabled subscription sources: %w", err)
	}
	if enabled >= MaximumEnabledSubscriptionSources {
		return fmt.Errorf("%w: enabled source count exceeds %d", ErrSubscriptionLimitExceeded, MaximumEnabledSubscriptionSources)
	}
	candidateBytes := int64(len(candidate.Config) + len(candidate.LatestSnapshot))
	return ensureSubscriptionInputBudget(ctx, q, "", excludeID, candidateBytes)
}

func ensureSubscriptionInputBudget(
	ctx context.Context,
	q queryRower,
	excludeChannelID string,
	excludeSourceID string,
	candidateBytes int64,
) error {
	var storedBytes int64
	if err := q.QueryRowContext(
		ctx,
		`SELECT
            coalesce((
                SELECT sum(length(config_json))
                  FROM subscription_channels
                 WHERE enabled = 1 AND id <> ?
            ), 0) +
            coalesce((
                SELECT sum(length(config_json) + coalesce(length(latest_snapshot_json), 0))
                  FROM subscription_sources
                 WHERE enabled = 1 AND id <> ?
            ), 0)`,
		excludeChannelID,
		excludeSourceID,
	).Scan(&storedBytes); err != nil {
		return fmt.Errorf("measure enabled subscription inputs: %w", err)
	}
	if candidateBytes < 0 || storedBytes > MaximumSubscriptionInputBytes-candidateBytes {
		return fmt.Errorf("%w: enabled input bytes exceed %d", ErrSubscriptionLimitExceeded, MaximumSubscriptionInputBytes)
	}
	return nil
}

func ensureChannelIdentityAvailable(
	ctx context.Context,
	q queryRower,
	id string,
	name string,
	excludeID string,
) error {
	var existingID string
	err := q.QueryRowContext(
		ctx,
		`SELECT id FROM subscription_channels
          WHERE (id = ? OR name = ?) AND id <> ?
          ORDER BY id LIMIT 1`,
		id,
		name,
		excludeID,
	).Scan(&existingID)
	if errors.Is(err, sql.ErrNoRows) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("check subscription channel identity: %w", err)
	}
	return fmt.Errorf("%w: id or name belongs to %s", ErrSubscriptionChannelExists, existingID)
}

func ensureSourceIdentityAvailable(
	ctx context.Context,
	q queryRower,
	id string,
	name string,
	excludeID string,
) error {
	var existingID string
	err := q.QueryRowContext(
		ctx,
		`SELECT id FROM subscription_sources
          WHERE (id = ? OR name = ?) AND id <> ?
          ORDER BY id LIMIT 1`,
		id,
		name,
		excludeID,
	).Scan(&existingID)
	if errors.Is(err, sql.ErrNoRows) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("check subscription source identity: %w", err)
	}
	return fmt.Errorf("%w: id or name belongs to %s", ErrSubscriptionSourceExists, existingID)
}

func ensureTokenIdentityAvailable(ctx context.Context, q queryRower, id string, digest string) error {
	var existingID string
	err := q.QueryRowContext(
		ctx,
		`SELECT id FROM subscription_tokens
          WHERE id = ? OR token_sha256 = ?
          ORDER BY id LIMIT 1`,
		id,
		digest,
	).Scan(&existingID)
	if errors.Is(err, sql.ErrNoRows) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("check subscription token identity: %w", err)
	}
	return fmt.Errorf("%w: id or digest belongs to %s", ErrSubscriptionTokenExists, existingID)
}

func insertSubscriptionToken(ctx context.Context, tx *sql.Tx, token SubscriptionToken) error {
	_, err := tx.ExecContext(
		ctx,
		`INSERT INTO subscription_tokens(
            id, token_sha256, expires_at, revoked_at, created_at
         ) VALUES (?, ?, ?, NULL, ?)`,
		token.ID,
		token.TokenSHA256,
		nullableSubscriptionTime(token.ExpiresAt),
		formatTaskTime(token.CreatedAt),
	)
	if err != nil {
		return fmt.Errorf("insert subscription token: %w", err)
	}
	return nil
}

func getSubscriptionChannel(ctx context.Context, q queryRower, id string) (SubscriptionChannel, error) {
	channel, err := scanSubscriptionChannel(q.QueryRowContext(
		ctx,
		`SELECT `+subscriptionChannelColumns+` FROM subscription_channels WHERE id = ?`,
		id,
	))
	if errors.Is(err, sql.ErrNoRows) {
		return SubscriptionChannel{}, fmt.Errorf("%w: %s", ErrSubscriptionChannelNotFound, id)
	}
	if err != nil {
		return SubscriptionChannel{}, fmt.Errorf("get subscription channel: %w", err)
	}
	return channel, nil
}

func scanSubscriptionChannel(row taskScanner) (SubscriptionChannel, error) {
	var channel SubscriptionChannel
	var config, createdAt, updatedAt string
	var enabled int
	if err := row.Scan(
		&channel.ID,
		&channel.Name,
		&channel.Format,
		&config,
		&enabled,
		&createdAt,
		&updatedAt,
	); err != nil {
		return SubscriptionChannel{}, err
	}
	channel.Config = append(json.RawMessage(nil), config...)
	channel.Enabled = enabled != 0
	var err error
	channel.CreatedAt, err = parseTaskTime(createdAt)
	if err != nil {
		return SubscriptionChannel{}, fmt.Errorf("parse created_at: %w", err)
	}
	channel.UpdatedAt, err = parseTaskTime(updatedAt)
	if err != nil {
		return SubscriptionChannel{}, fmt.Errorf("parse updated_at: %w", err)
	}
	return channel, nil
}

func scanSubscriptionChannelSummary(row taskScanner) (SubscriptionChannelSummary, error) {
	var channel SubscriptionChannelSummary
	var createdAt, updatedAt string
	var enabled int
	if err := row.Scan(
		&channel.ID,
		&channel.Name,
		&channel.Format,
		&enabled,
		&createdAt,
		&updatedAt,
	); err != nil {
		return SubscriptionChannelSummary{}, err
	}
	channel.Enabled = enabled != 0
	var err error
	channel.CreatedAt, err = parseTaskTime(createdAt)
	if err != nil {
		return SubscriptionChannelSummary{}, fmt.Errorf("parse created_at: %w", err)
	}
	channel.UpdatedAt, err = parseTaskTime(updatedAt)
	if err != nil {
		return SubscriptionChannelSummary{}, fmt.Errorf("parse updated_at: %w", err)
	}
	return channel, nil
}

func getSubscriptionSource(ctx context.Context, q queryRower, id string) (SubscriptionSource, error) {
	source, err := scanSubscriptionSource(q.QueryRowContext(
		ctx,
		`SELECT `+subscriptionSourceColumns+` FROM subscription_sources WHERE id = ?`,
		id,
	))
	if errors.Is(err, sql.ErrNoRows) {
		return SubscriptionSource{}, fmt.Errorf("%w: %s", ErrSubscriptionSourceNotFound, id)
	}
	if err != nil {
		return SubscriptionSource{}, fmt.Errorf("get subscription source: %w", err)
	}
	return source, nil
}

func scanSubscriptionSource(row taskScanner) (SubscriptionSource, error) {
	var source SubscriptionSource
	var config, createdAt, updatedAt string
	var snapshot sql.NullString
	var enabled int
	if err := row.Scan(
		&source.ID,
		&source.Name,
		&source.SourceKind,
		&config,
		&snapshot,
		&enabled,
		&createdAt,
		&updatedAt,
	); err != nil {
		return SubscriptionSource{}, err
	}
	source.Config = append(json.RawMessage(nil), config...)
	if snapshot.Valid {
		source.LatestSnapshot = append(json.RawMessage(nil), snapshot.String...)
	}
	source.Enabled = enabled != 0
	var err error
	source.CreatedAt, err = parseTaskTime(createdAt)
	if err != nil {
		return SubscriptionSource{}, fmt.Errorf("parse created_at: %w", err)
	}
	source.UpdatedAt, err = parseTaskTime(updatedAt)
	if err != nil {
		return SubscriptionSource{}, fmt.Errorf("parse updated_at: %w", err)
	}
	return source, nil
}

func scanSubscriptionSourceSummary(row taskScanner) (SubscriptionSourceSummary, error) {
	var source SubscriptionSourceSummary
	var hasSnapshot, enabled int
	var createdAt, updatedAt string
	if err := row.Scan(
		&source.ID,
		&source.Name,
		&source.SourceKind,
		&hasSnapshot,
		&enabled,
		&createdAt,
		&updatedAt,
	); err != nil {
		return SubscriptionSourceSummary{}, err
	}
	source.HasSnapshot = hasSnapshot != 0
	source.Enabled = enabled != 0
	var err error
	source.CreatedAt, err = parseTaskTime(createdAt)
	if err != nil {
		return SubscriptionSourceSummary{}, fmt.Errorf("parse created_at: %w", err)
	}
	source.UpdatedAt, err = parseTaskTime(updatedAt)
	if err != nil {
		return SubscriptionSourceSummary{}, fmt.Errorf("parse updated_at: %w", err)
	}
	return source, nil
}

func getSubscriptionToken(ctx context.Context, q queryRower, id string) (SubscriptionToken, error) {
	token, err := scanSubscriptionToken(q.QueryRowContext(
		ctx,
		`SELECT `+subscriptionTokenColumns+` FROM subscription_tokens WHERE id = ?`,
		id,
	))
	if errors.Is(err, sql.ErrNoRows) {
		return SubscriptionToken{}, fmt.Errorf("%w: %s", ErrSubscriptionTokenNotFound, id)
	}
	if err != nil {
		return SubscriptionToken{}, fmt.Errorf("get subscription token: %w", err)
	}
	return token, nil
}

func scanSubscriptionToken(row taskScanner) (SubscriptionToken, error) {
	var token SubscriptionToken
	var expiresAt, revokedAt sql.NullString
	var createdAt string
	if err := row.Scan(
		&token.ID,
		&token.TokenSHA256,
		&expiresAt,
		&revokedAt,
		&createdAt,
	); err != nil {
		return SubscriptionToken{}, err
	}
	var err error
	token.CreatedAt, err = parseTaskTime(createdAt)
	if err != nil {
		return SubscriptionToken{}, fmt.Errorf("parse created_at: %w", err)
	}
	if expiresAt.Valid {
		parsed, err := parseTaskTime(expiresAt.String)
		if err != nil {
			return SubscriptionToken{}, fmt.Errorf("parse expires_at: %w", err)
		}
		token.ExpiresAt = &parsed
	}
	if revokedAt.Valid {
		parsed, err := parseTaskTime(revokedAt.String)
		if err != nil {
			return SubscriptionToken{}, fmt.Errorf("parse revoked_at: %w", err)
		}
		token.RevokedAt = &parsed
	}
	return token, nil
}

func validateSubscriptionID(value string, kind string) error {
	if value == "" || value != strings.TrimSpace(value) || len(value) > 128 || strings.ContainsRune(value, '\x00') {
		return fmt.Errorf("subscription %s id is invalid", kind)
	}
	return nil
}

func validateSubscriptionName(value string) error {
	if value == "" || value != strings.TrimSpace(value) || len(value) > maximumSubscriptionNameBytes ||
		!utf8.ValidString(value) {
		return errors.New("subscription name must be normalized non-empty UTF-8 of at most 128 bytes")
	}
	for _, character := range value {
		if unicode.IsControl(character) {
			return errors.New("subscription name contains a control character")
		}
	}
	return nil
}

func validSubscriptionFormat(value SubscriptionFormat) bool {
	return value == SubscriptionFormatSingBox || value == SubscriptionFormatMihomo || value == SubscriptionFormatLoon
}

func validSubscriptionSourceKind(value SubscriptionSourceKind) bool {
	return value == SubscriptionSourceRemote || value == SubscriptionSourceLocal
}

func validateUniqueSubscriptionStrings(
	values []string,
	valid func(string) bool,
	kind string,
) error {
	seen := make(map[string]struct{}, len(values))
	for _, value := range values {
		if !valid(value) {
			return fmt.Errorf("subscription channel config contains an invalid %s exclusion", kind)
		}
		if _, duplicate := seen[value]; duplicate {
			return fmt.Errorf("subscription channel config contains a duplicate %s exclusion", kind)
		}
		seen[value] = struct{}{}
	}
	return nil
}

func validSubscriptionTag(value string) bool {
	return value != "" && len(value) <= 512 && utf8.ValidString(value) && !strings.ContainsRune(value, '\x00')
}

func validSubscriptionType(value string) bool {
	if value == "" || len(value) > 64 {
		return false
	}
	for _, character := range value {
		if (character >= 'a' && character <= 'z') || (character >= '0' && character <= '9') ||
			character == '-' || character == '_' {
			continue
		}
		return false
	}
	return true
}

func normalizeTokenDigest(value string) (string, error) {
	if len(value) != sha256.Size*2 || strings.ToLower(value) != value {
		return "", errors.New("subscription token digest must be lowercase SHA-256")
	}
	decoded, err := hex.DecodeString(value)
	if err != nil || len(decoded) != sha256.Size {
		return "", errors.New("subscription token digest must be lowercase SHA-256")
	}
	return value, nil
}

func requiredUTC(value time.Time, name string) (time.Time, error) {
	if value.IsZero() {
		return time.Time{}, fmt.Errorf("%s is required", name)
	}
	return value.UTC(), nil
}

func nextSubscriptionUpdateTime(value time.Time, expected time.Time) (time.Time, error) {
	value, err := requiredUTC(value, "subscription updated_at")
	if err != nil {
		return time.Time{}, err
	}
	if !value.After(expected) {
		return time.Time{}, errors.New("subscription updated_at must advance beyond expected updated_at")
	}
	return value, nil
}

func subscriptionConflict(resource string, id string, expected, actual time.Time) error {
	return &SubscriptionConflictError{
		Resource: resource,
		ID:       id,
		Expected: expected,
		Actual:   actual,
	}
}

func requireSingleSubscriptionWrite(result sql.Result, operation string) error {
	rows, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("inspect %s: %w", operation, err)
	}
	if rows != 1 {
		return fmt.Errorf("%s affected %d rows, want 1", operation, rows)
	}
	return nil
}

func nullableRawJSON(value json.RawMessage) any {
	if len(value) == 0 {
		return nil
	}
	return string(value)
}

func nullableSubscriptionTime(value *time.Time) any {
	if value == nil {
		return nil
	}
	return formatTaskTime(*value)
}
