export const channels = {
  members: 'Group members', membersCount: '{{count}} nodes', finalExit: 'Final exit', createFirstGroup: 'Create first group', searchNodes: 'Search nodes, sources or protocols', noMatchingNodes: 'No matching nodes', searchNodesHint: 'Try another name, source or protocol.', ruleSet: 'Rule set',
  newGroupName: 'Strategy group {{number}}', groupSummary: '{{nodes}} nodes · {{rules}} rules', nodeCount: '{{count}} selected', noGroups: 'No strategy groups yet', noGroupsHint: 'Add a group on the left, then choose its nodes and traffic exits.', noNodes: 'No nodes available. Add nodes in Subscription sources.', noRules: 'Add rules to match traffic and choose an exit. Rules are evaluated in order.', nodeExitInUse: 'This node is used by an exit. Change the default exit or matching rules before removing it.', groupExitInUse: 'This group handles unmatched traffic. Choose another fallback before deleting or disabling it.', moveGroupUp: 'Move group up', moveGroupDown: 'Move group down',
  subscriptionKey: 'Subscription key', keyPlaceholder: 'Paste an existing key', keyHint: 'Create keys in Key management. The same key can be used with multiple channels; it is not saved here.', copyURL: 'Copy subscription URL', saveBeforeCopy: 'Save channel changes before copying the subscription URL.', channelUnavailable: 'This channel is disabled and cannot distribute subscriptions.',
  disabled: 'Disabled',
  title: 'Channels', search: 'Search channels', add: 'Add channel', name: 'Channel name', client: 'Output client', edit: 'Edit', remove: 'Delete channel', deletePrompt: 'Delete “{{name}}”? Its subscription URL will become unavailable.', save: 'Save changes', saved: 'Channel saved', empty: 'No channels', back: 'Back', nodes: 'Node selection', rules: 'Strategy groups', organizer: 'Organize nodes', distribution: 'Distribution settings', preview: 'Subscription preview', enabled: 'Enabled', nameRequired: 'Enter a name', unsaved: 'Unsaved changes', discard: 'Discard changes', leave: 'Discard unsaved channel changes?', cancel: 'Cancel', done: 'Done', refresh: 'Refresh nodes',
  prefix: 'Name prefix', exclusions: 'Exclude names', exclusionsHint: 'One per line', sort: 'Node order', original: 'Original order', byName: 'By name', deduplicate: 'Deduplicate', incompatible: 'Incompatible nodes', skip: 'Skip with diagnostic', stop: 'Block generation', legacyTags: 'Exclude tags', legacyTypes: 'Exclude protocols',
  newNodes: 'New-node policy', include: 'Include automatically', exclude: 'Select manually', template: 'Current template', defaultTemplate: 'Default configuration', customTemplate: 'Custom configuration', editTemplate: 'Edit template', templateCode: 'Native configuration', validate: 'Validate', valid: 'Template structure is valid', templateSaved: 'Template saved', saveTemplate: 'Save template', formatConflict: 'Output client changed. Review rule-set formats and template.', copy: 'Copy', copied: 'Copied', failedNodes: '{{count}} nodes were omitted. See diagnostics.', diagnostics: 'Generation diagnostics',
  groups: 'Strategy groups', addGroup: 'Add strategy group', editGroup: 'Edit strategy group', groupName: 'Group name', matches: 'Exit rules', manualCount: '{{count}} rules', remoteCount: '{{count}} rule sets', state: 'State', actions: 'Actions', candidates: 'Candidate nodes', defaultExit: 'Default exit', fallback: 'Unmatched traffic', direct: 'Direct', reject: 'Reject', follow: 'Group default', missingNode: 'Unavailable node', moveUp: 'Move up', moveDown: 'Move down', deleteGroup: 'Delete strategy group', deleteRule: 'Delete rule',
  addRule: 'Add rule', addRemote: 'Add rule set', editRule: 'Edit rule', editRemote: 'Edit rule set', ruleKind: 'Match type', domain: 'Domain', domain_suffix: 'Domain suffix', domain_keyword: 'Domain keyword', ip_cidr: 'IP / CIDR', matchValue: 'Match value', exit: 'Traffic exit', ruleName: 'Name', url: 'Source URL', acceleration: 'Accelerate GitHub file', sourceFormat: 'Source format', chooseFormat: 'Choose format', behavior: 'Rule behavior', interval: 'Update interval (seconds)', selectAll: 'Select all', selectNone: 'Clear selection', unavailable: 'Currently unavailable', invalidRule: 'Check the match value, source URL or update interval.', formatPending: 'Choose a compatible format',
  legacy: 'This channel retains Loon output. Switch client and save to use rules and templates.', publicHost: 'Existing channel public host', enabledLabel: 'Channel enabled', selectedByGroup: 'This node is referenced by a group or default exit. Adjust those exits first.', legacyFilters: 'Existing exclusions',
} as const;
